using System.Collections.Generic;

namespace ElementalHearts.Common.Hearts;

/// <summary>
/// Curated elemental-power names shown in the activated tooltip for each heart.
/// </summary>
internal static class ElementalPowerRegistry
{
	private static readonly Dictionary<string, string> Powers = new()
	{
		// ── Common ──────────────────────────────────────────────────────────────
		["BubbleHeart"] = "bubble",
		["BorealWoodHeart"] = "boreal",
		["CactusHeart"] = "cactus",
		["CandyCaneHeart"] = "peppermint",
		["CloudHeart"] = "cloud",
		["CoralstoneHeart"] = "coral",
		["CrimsandHeart"] = "crimsand",
		["CrimstoneHeart"] = "carnage",
		["DirtHeart"] = "earth",
		["DynastyHeart"] = "dynasty",
		["EbonsandHeart"] = "ebon",
		["EbonstoneHeart"] = "corruption",
		["EbonwoodHeart"] = "shadowwood",
		["FleshHeart"] = "flesh",
		["FossilHeart"] = "fossil",
		["GlassHeart"] = "glass",
		["GraniteHeart"] = "granite",
		["HayHeart"] = "straw",
		["HoneyHeart"] = "honey",
		["IceHeart"] = "ice",
		["MarbleHeart"] = "marble",
		["MudHeart"] = "mud",
		["MushroomHeart"] = "spore",
		["ObsidianHeart"] = "obsidian",
		["PalmWoodHeart"] = "palm",
		["PearlsandHeart"] = "shimmer",
		["PearlstoneHeart"] = "hallow",
		["PearlwoodHeart"] = "pearlwood",
		["PinkIceHeart"] = "bloom",
		["PumpkinHeart"] = "pumpkin",
		["PurpleIceHeart"] = "amethyst frost",
		["RainbowHeart"] = "rainbow",
		["RainCloudHeart"] = "rain",
		["RedIceHeart"] = "scarlet frost",
		["RichMahoganyHeart"] = "mahogany",
		["SandHeart"] = "sand",
		["ShadewoodHeart"] = "shade",
		["SlimeHeart"] = "slime",
		["SnowCloudHeart"] = "flurry",
		["SnowHeart"] = "snow",
		["SpookyHeart"] = "spooky",
		["StoneHeart"] = "stone",
		["SunplateHeart"] = "heaven",
		["WoodHeart"] = "wood",

		// ── Uncommon ────────────────────────────────────────────────────────────
		["AmethystHeart"] = "amethyst",
		["CopperHeart"] = "copper",
		["EmeraldHeart"] = "emerald",
		["GoldHeart"] = "gold",
		["IronHeart"] = "iron",
		["LeadHeart"] = "lead",
		["PlatinumHeart"] = "platinum",
		["RubyHeart"] = "ruby",
		["SapphireHeart"] = "sapphire",
		["SilverHeart"] = "silver",
		["TinHeart"] = "tin",
		["TopazHeart"] = "topaz",
		["TungstenHeart"] = "tungsten",

		// ── Rare ──────────────────────────────────────────────────────────────────
		["AmberHeart"] = "amber",
		["BrainHeart"] = "brain",
		["CobaltHeart"] = "cobalt",
		["CogHeart"] = "gears",
		["CrimtaneHeart"] = "crimson",
		["CrystalHeart"] = "crystal",
		["CursedFlameHeart"] = "hellfire",
		["DarkHeart"] = "shadow",
		["DemoniteHeart"] = "demon",
		["DiamondHeart"] = "diamond",
		["DiscordHeart"] = "chaos",
		["EnchantedHeart"] = "arcane",
		["HellstoneHeart"] = "hellstone",
		["IchorHeart"] = "ichor",
		["LesionHeart"] = "lesion",
		["MeteoriteHeart"] = "meteor",
		["MythrilHeart"] = "mythril",
		["OrichalcumHeart"] = "orichalcum",
		["PalladiumHeart"] = "palladium",
		["SoulOfFlightHeart"] = "wind",
		["SoulOfFrightHeart"] = "terror",
		["SoulOfLightHeart"] = "light",
		["SoulOfMightHeart"] = "power",
		["SoulOfNightHeart"] = "night",
		["SoulOfSightHeart"] = "vision",
		["WormHeart"] = "devourer",

		// ── Epic ──────────────────────────────────────────────────────────────────
		["AdamantiteHeart"] = "adamantite",
		["ChlorophyteHeart"] = "jungle",
		["HallowedHeart"] = "blessing",
		["TitaniumHeart"] = "titanium",

		// ── Legendary ─────────────────────────────────────────────────────────────
		["EctoplasmHeart"] = "spirit",
		["LuminiteHeart"] = "starlight",
		["ShroomiteHeart"] = "shroomite",
		["SpectreHeart"] = "spectre",

		// ── Exotic (boss-themed) ──────────────────────────────────────────────────
		["AncientHeart"] = "sun",
		["BetsyHeart"] = "dragon",
		["BlizzardHeart"] = "blizzard",
		["BoneHeart"] = "skeleton",
		["CelestialHeart"] = "moon",
		["DeerclopsHeart"] = "deerclops",
		["DukeFishronHeart"] = "fishron",
		["ElfHeart"] = "yule",
		["EmpressHeart"] = "prism",
		["EyeHeart"] = "cthulhu",
		["FlyingDutchmanHeart"] = "pirate",
		["HiveHeart"] = "bee",
		["HorsemanHeart"] = "reaper",
		["LihzahrdHeart"] = "golem",
		["MechanicalHeart"] = "mech",
		["MenacingHeart"] = "menace",
		["MourningWoodHeart"] = "ember",
		["PlantHeart"] = "plantera",
		["QueenSlimeHeart"] = "queen",
		["RazorpineHeart"] = "razor",
		["RoyalSlimeHeart"] = "monarch",
		["SlaughterHeart"] = "destroyer",
		["SnotHeart"] = "tissue",
		["SoaringHeart"] = "soar",
		["TruffleHeart"] = "truffle",
		["VolatileHeart"] = "world eater",
		["WallOfFleshHeart"] = "underworld",
		["XenoHeart"] = "alien",

		// ── Mythic ──────────────────────────────────────────────────────────────────
		["ZenithHeart"] = "zenith",

		// ── Cross-mod: Calamity ─────────────────────────────────────────────────────
		["AbyssGravelHeart"] = "abyss",
		["AerialiteHeart"] = "aerial",
		["AfflictedHeart"] = "plague",
		["AmbergrisHeart"] = "whale",
		["AquaticHeart"] = "leviathan",
		["ArmoredHeart"] = "bronze",
		["AstralBossHeart"] = "aureus",
		["AstralClayHeart"] = "stardust clay",
		["AstralDirtHeart"] = "stardust",
		["AstralHeart"] = "stars",
		["AstralIceHeart"] = "comet",
		["AstralMonolithHeart"] = "monolith",
		["AstralSandHeart"] = "star sand",
		["AstralSandstoneHeart"] = "starstone",
		["AstralSnowHeart"] = "starfall",
		["AstralStoneHeart"] = "meteorite",
		["AuricHeart"] = "divinity",
		["BlazingHeart"] = "inferno",
		["BloodyWormHeart"] = "blood worm",
		["BrimstoneSlagHeart"] = "brimstone",
		["CalamitousHeart"] = "calamity",
		["CelestialRemainsHeart"] = "remnant",
		["CinderplateHeart"] = "cinder",
		["CorpusHeart"] = "bloodstone",
		["CosmiliteHeart"] = "cosmos",
		["CryogenHeart"] = "cryogen",
		["CryonicHeart"] = "frost",
		["CrystallizedToxicHeart"] = "toxin",
		["DarkPlasmicHeart"] = "plasma",
		["DraconicHeart"] = "wyrm",
		["DynamoStemHeart"] = "energy",
		["EutrophicSandHeart"] = "vitality",
		["ExodiumClusterHeart"] = "exodium",
		["FungalHeart"] = "fungus",
		["GehennaHeart"] = "gehenna",
		["GravistarHeart"] = "gravity",
		["HardenedAstralSandHeart"] = "hardened void",
		["HardenedSulphurousSandstoneHeart"] = "sulphur stone",
		["MutatedHeart"] = "mutation",
		["NavystoneHeart"] = "tide",
		["NebulousHeart"] = "nebula",
		["NovaeSlugHeart"] = "nova",
		["OceanHeart"] = "trench",
		["PerennialHeart"] = "perennial",
		["PlantyMushHeart"] = "mycelium",
		["PolarizedHeart"] = "polarity",
		["ProfanedHeart"] = "providence",
		["RottenHeart"] = "rot",
		["ScoriaHeart"] = "scoria",
		["SeaPrismHeart"] = "reef",
		["SulphurousSandHeart"] = "sulphur",
		["SulphurousSandstoneHeart"] = "sulphur sand",
		["TenebrisHeart"] = "darkness",
		["TwistingHeart"] = "twist",
		["UelibloomHeart"] = "uelibloom",
		["VoidstoneHeart"] = "void",

		// ── Cross-mod: Consolaria ─────────────────────────────────────────────────
		["CornucopiaHeart"] = "abundance",
		["CursedHeart"] = "omen",
		["EasterHeart"] = "spring",
		["SoulOfBlightHeart"] = "blight",

		// ── Cross-mod: Thorium ────────────────────────────────────────────────────
		["AbyssalHeart"] = "depths",
		["AquaiteHeart"] = "aqua",
		["BeholderHeart"] = "beholder",
		["BrackishClumpHeart"] = "brine",
		["ChampionHeart"] = "champion",
		["DepthsRockHeart"] = "depths rock",
		["DormantHeart"] = "slumber",
		["IceboundStriderHeart"] = "strider",
		["IllumiteHeart"] = "illumite",
		["LifeQuartzHeart"] = "life quartz",
		["LichHeart"] = "lich",
		["LodestoneHeart"] = "magnetism",
		["MagmaHeart"] = "magma",
		["MossyMarineRockHeart"] = "tidepool",
		["OmegaHeart"] = "omega",
		["OnyxHeart"] = "onyx",
		["OpalHeart"] = "opal",
		["PearlHeart"] = "pearl",
		["PermafrostHeart"] = "permafrost",
		["SeaBreezeHeart"] = "breeze",
		["SmoothCoalHeart"] = "coal",
		["StormHeart"] = "storm",
		["ThoriumHeart"] = "thorium",
		["ValadiumHeart"] = "valadium",
		["VampireHeart"] = "vampire",
		["YewWoodHeart"] = "yew",
		["ZephyrHeart"] = "zephyr",
	};

	public static string Get(string heartName) =>
		Powers.TryGetValue(heartName, out string power) ? power : heartName.ToLowerInvariant();
}
