using System.Collections.Generic;

namespace ElementalHearts.Common.Hearts;

/// <summary>
/// Curated elemental-power names shown in the activated tooltip for each heart.
/// </summary>
internal static class ElementalPowerRegistry
{
	private static readonly Dictionary<string, string> Powers = new()
	{
		// ── Common ──────────────────────────────────────────────────────────────
		["AcornHeart"] = "harvest",
		["BubbleHeart"] = "bubble",
		["BorealWoodHeart"] = "boreal",
		["CactusHeart"] = "cactus",
		["CandyCaneHeart"] = "peppermint",
		["CloudHeart"] = "cloud",
		["CoralstoneHeart"] = "coral",
		["CrimsandHeart"] = "crimsand",
		["CrimstoneHeart"] = "carnage",
		["DirtHeart"] = "earth",
		["DynastyHeart"] = "dynasty",
		["EbonsandHeart"] = "ebon",
		["EbonstoneHeart"] = "corruption",
		["EbonwoodHeart"] = "shadowwood",
		["FleshHeart"] = "flesh",
		["FossilHeart"] = "fossil",
		["GemcornHeart"] = "gemcorn",
		["GlassHeart"] = "glass",
		["GraniteHeart"] = "granite",
		["HayHeart"] = "straw",
		["HoneyHeart"] = "honey",
		["IceHeart"] = "ice",
		["MarbleHeart"] = "marble",
		["MudHeart"] = "mud",
		["MushroomHeart"] = "spore",
		["ObsidianHeart"] = "obsidian",
		["PalmWoodHeart"] = "palm",
		["PearlsandHeart"] = "shimmer",
		["PearlstoneHeart"] = "hallow",
		["PearlwoodHeart"] = "pearlwood",
		["PinkIceHeart"] = "bloom",
		["PumpkinHeart"] = "pumpkin",
		["PurpleIceHeart"] = "amethyst frost",
		["RainbowHeart"] = "rainbow",
		["RainCloudHeart"] = "rain",
		["RedIceHeart"] = "scarlet frost",
		["RichMahoganyHeart"] = "mahogany",
		["SandHeart"] = "sand",
		["ShadewoodHeart"] = "shade",
		["SlimeHeart"] = "slime",
		["SnowCloudHeart"] = "flurry",
		["SnowHeart"] = "snow",
		["SpookyHeart"] = "spooky",
		["StoneHeart"] = "stone",
		["SunplateHeart"] = "heaven",
		["WoodHeart"] = "wood",

		// ── Uncommon ────────────────────────────────────────────────────────────
		["AmethystHeart"] = "amethyst",
		["CopperHeart"] = "copper",
		["EmeraldHeart"] = "emerald",
		["GoldHeart"] = "gold",
		["IronHeart"] = "iron",
		["LeadHeart"] = "lead",
		["PlatinumHeart"] = "platinum",
		["RubyHeart"] = "ruby",
		["SapphireHeart"] = "sapphire",
		["SilverHeart"] = "silver",
		["TinHeart"] = "tin",
		["TopazHeart"] = "topaz",
		["TungstenHeart"] = "tungsten",

		// ── Rare ──────────────────────────────────────────────────────────────────
		["AmberHeart"] = "amber",
		["BrainHeart"] = "brain",
		["CobaltHeart"] = "cobalt",
		["CogHeart"] = "gears",
		["CrimtaneHeart"] = "crimson",
		["CrystalHeart"] = "life crystal",
		["LifeFruitHeart"] = "life fruit",
		["CursedFlameHeart"] = "hellfire",
		["DarkHeart"] = "shadow",
		["DemoniteHeart"] = "demon",
		["DiamondHeart"] = "diamond",
		["DiscordHeart"] = "chaos",
		["EnchantedHeart"] = "arcane",
		["HellstoneHeart"] = "hellstone",
		["IchorHeart"] = "ichor",
		["LesionHeart"] = "lesion",
		["MeteoriteHeart"] = "meteor",
		["MythrilHeart"] = "mythril",
		["OrichalcumHeart"] = "orichalcum",
		["PalladiumHeart"] = "palladium",
		["SoulOfFlightHeart"] = "wind",
		["SoulOfFrightHeart"] = "terror",
		["SoulOfLightHeart"] = "light",
		["SoulOfMightHeart"] = "power",
		["SoulOfNightHeart"] = "night",
		["SoulOfSightHeart"] = "vision",
		["WormHeart"] = "devourer",

		// ── Epic ──────────────────────────────────────────────────────────────────
		["AdamantiteHeart"] = "adamantite",
		["ChlorophyteHeart"] = "jungle",
		["HallowedHeart"] = "blessing",
		["MechanicalHeart"] = "mech",
		["TitaniumHeart"] = "titanium",

		// ── Legendary ─────────────────────────────────────────────────────────────
		["EctoplasmHeart"] = "spirit",
		["LuminiteHeart"] = "starlight",
		["ShroomiteHeart"] = "shroomite",
		["SpectreHeart"] = "spectre",
		// Lunar bricks — each is a moon-phase joke (work, comedy timing, royalty, decay)
		["AstraHeart"] = "moonlighting",         // Third Quarter — late shift / second job by moonlight
		["CosmicEmberHeart"] = "slow burn",      // Waxing Gibbous — slow growth + ember combustion
		["CryocoreHeart"] = "cold open",         // First Quarter — the opening; comedy term + literally cold
		["DarkCelestialHeart"] = "lights out",   // Waning Crescent — almost-gone moon = bedtime
		["HeavenforgeHeart"] = "overtime",       // Full Moon — peak shift at the celestial forge
		["LunarRustHeart"] = "moonrot",          // Waning Gibbous — wane = decay; rust pun
		["MercuryHeart"] = "mood swing",         // New Moon — mercurial + dark new-moon mood
		["StarRoyaleHeart"] = "moonarch",        // Waxing Crescent — moon + monarch; crescent = crown

		// ── Exotic (boss-themed) ──────────────────────────────────────────────────
		["BetsyHeart"] = "dragon",
		["BrainOfCthulhuHeart"] = "tissue",
		["DeerclopsHeart"] = "deerclops",
		["DestroyerHeart"] = "destroyer",
		["DukeFishronHeart"] = "fishron",
		["ElfHeart"] = "yule",
		["EmpressOfLightHeart"] = "prism",
		["EyeOfCthulhuHeart"] = "cthulhu",
		["FlyingDutchmanHeart"] = "pirate",
		["GolemHeart"] = "golem",
		["JackOLanternHeart"] = "all hallows",
		["KingSlimeHeart"] = "monarch",
		["LunaticCultistHeart"] = "sun",
		["MartianSaucerHeart"] = "alien",
		["MoonLordHeart"] = "moon",
		["MourningWoodHeart"] = "ember",
		["PlanteraHeart"] = "plantera",
		["PumpkingHeart"] = "reaper",
		["QueenBeeHeart"] = "bee",
		["QueenSlimeHeart"] = "queen",
		["RazorpineHeart"] = "razor",
		["SkeletronHeart"] = "skeleton",
		["WallOfFleshHeart"] = "underworld",

		// ── Mythic ──────────────────────────────────────────────────────────────────
		["ZenithHeart"] = "zenith",

		// ── Cross-mod: Calamity ─────────────────────────────────────────────────────
		["AbyssGravelHeart"] = "abyss",
		["AerialiteHeart"] = "aerial",
		["AfflictedHeart"] = "plague",
		["AmbergrisHeart"] = "whale",
		["AquaticHeart"] = "leviathan",
		["ArmoredHeart"] = "bronze",
		["AstralBossHeart"] = "aureus",
		["AstralClayHeart"] = "stardust clay",
		["AstralDirtHeart"] = "stardust",
		["AstralHeart"] = "stars",
		["AstralIceHeart"] = "comet",
		["AstralMonolithHeart"] = "monolith",
		["AstralSandHeart"] = "star sand",
		["AstralSandstoneHeart"] = "starstone",
		["AstralSnowHeart"] = "starfall",
		["AstralStoneHeart"] = "meteorite",
		["AuricHeart"] = "divinity",
		["BlazingHeart"] = "inferno",
		["BloodyWormHeart"] = "blood worm",
		["BrimstoneSlagHeart"] = "brimstone",
		["CalamitousHeart"] = "calamity",
		["CelestialRemainsHeart"] = "remnant",
		["CinderplateHeart"] = "cinder",
		["CorpusHeart"] = "bloodstone",
		["CosmiliteHeart"] = "cosmos",
		["CryogenHeart"] = "cryogen",
		["CryonicHeart"] = "frost",
		["CrystallizedToxicHeart"] = "toxin",
		["DarkPlasmicHeart"] = "plasma",
		["DraconicHeart"] = "wyrm",
		["DynamoStemHeart"] = "energy",
		["EutrophicSandHeart"] = "vitality",
		["ExodiumClusterHeart"] = "exodium",
		["FungalHeart"] = "fungus",
		["GehennaHeart"] = "gehenna",
		["GravistarHeart"] = "gravity",
		["HardenedAstralSandHeart"] = "hardened void",
		["MutatedHeart"] = "mutation",
		["NavystoneHeart"] = "tide",
		["NebulousHeart"] = "nebula",
		["NovaeSlugHeart"] = "nova",
		["OceanHeart"] = "trench",
		["PerennialHeart"] = "perennial",
		["PlantyMushHeart"] = "mycelium",
		["PolarizedHeart"] = "polarity",
		["ProfanedHeart"] = "providence",
		["RottenHeart"] = "rot",
		["ScoriaHeart"] = "scoria",
		["SeaPrismHeart"] = "reef",
		["SulphurousSandHeart"] = "sulphur",
		["SulphurousSandstoneHeart"] = "sulphur sand",
		["TenebrisHeart"] = "darkness",
		["TwistingHeart"] = "twist",
		["UelibloomHeart"] = "uelibloom",
		["VoidstoneHeart"] = "void",

		// ── Cross-mod: Consolaria ─────────────────────────────────────────────────
		["CornucopiaHeart"] = "abundance",
		["CursedHeart"] = "omen",
		["EasterHeart"] = "spring",
		["SoulOfBlightHeart"] = "blight",

		// ── Vanilla: Potion Hearts ────────────────────────────────────────────────
		["AmmoReservationHeart"]  = "munition",
		["ArcheryHeart"]          = "archery",
		["BattleHeart"]           = "battle",
		["BiomeSightHeart"]       = "panorama",
		["BuilderHeart"]          = "construction",
		["CalmingHeart"]          = "tranquility",
		["CrateHeart"]            = "cratemania",
		["DangersenseHeart"]      = "dangersense",
		["EnduranceHeart"]        = "endurance",
		["FeatherfallHeart"]      = "feather",
		["FishingHeart"]          = "angler",
		["FlipperHeart"]          = "flipper",
		["GillsHeart"]            = "gills",
		["GravitationHeart"]      = "gravity",
		["HeartreachHeart"]       = "heartreach",
		["HunterHeart"]           = "hunter",
		["InfernoHeart"]          = "inferno",
		["IronskinHeart"]         = "ironskin",
		["LifeforceHeart"]        = "lifeforce",
		["LoveHeart"]             = "infatuation",
		["MagicPowerHeart"]       = "arcanum",
		["ManaRegenerationHeart"] = "mana flow",
		["MiningHeart"]           = "prospector",
		["NightOwlHeart"]         = "nightsight",
		["ObsidianSkinHeart"]     = "obsidian skin",
		["RageHeart"]             = "rage",
		["RegenerationHeart"]     = "regeneration",
		["ShineHeart"]            = "shine",
		["SonarHeart"]            = "sonar",
		["SpelunkerHeart"]        = "spelunker",
		["StinkHeart"]            = "stench",
		["SummoningHeart"]        = "summoning",
		["SwiftnessHeart"]        = "swiftness",
		["ThornsHeart"]           = "thorns",
		["TitanHeart"]            = "titan",
		["WarmthHeart"]           = "warmth",
		["WaterWalkingHeart"]     = "water walking",
		["WrathHeart"]            = "wrath",

		// ── Cross-mod: Thorium ────────────────────────────────────────────────────
		["AbyssalHeart"] = "depths",
		["AquaiteHeart"] = "aqua",
		["BeholderHeart"] = "beholder",
		["BrackishClumpHeart"] = "brine",
		["ChampionHeart"] = "champion",
		["DepthsRockHeart"] = "depths rock",
		["DormantHeart"] = "slumber",
		["IceboundStriderHeart"] = "strider",
		["IllumiteHeart"] = "illumite",
		["LifeQuartzHeart"] = "life quartz",
		["LichHeart"] = "lich",
		["LodestoneHeart"] = "magnetism",
		["MagmaHeart"] = "magma",
		["MossyMarineRockHeart"] = "tidepool",
		["OmegaHeart"] = "omega",
		["OnyxHeart"] = "onyx",
		["OpalHeart"] = "opal",
		["PearlHeart"] = "pearl",
		["PermafrostHeart"] = "permafrost",
		["SeaBreezeHeart"] = "breeze",
		["SmoothCoalHeart"] = "coal",
		["StormHeart"] = "storm",
		["ThoriumHeart"] = "thorium",
		["ValadiumHeart"] = "valadium",
		["VampireHeart"] = "vampire",
		["YewWoodHeart"] = "yew",
		["ZephyrHeart"] = "zephyr",
	};

	public static string Get(string heartName) =>
		Powers.TryGetValue(heartName, out string power) ? power : heartName.ToLowerInvariant();
}
